---
name: CI

on:
  push:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run : |
          bandit app.py

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run : |
          python -m pytest

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          echo $PAT | docker login ghcr.io -u yanpingfANG --password-stdin
          docker build --build-arg APP_VERSION="$APP_VERSION" -t $CONTAINER_COMMIT_IMAGE  -t $CONTAINER_LATEST_IMAGE .
          docker push $CONTAINER_COMMIT_IMAGE
          docker push $CONTAINER_LATEST_IMAGE
        env:
          PAT: ${{ secrets.DOJO }}
          APP_VERSION: ${{ github.sha }}
          CONTAINER_REGISTRY: ghcr.io/yanpingfANG/github-actions-dojo
          CONTAINER_COMMIT_IMAGE: ghcr.io/yanpingfANG/github-actions-dojo:${{ github.sha }}
          CONTAINER_LATEST_IMAGE: ghcr.io/yanpingfANG/github-actions-dojo:latest
